### ISSUE TITLE
Composer script

### ISSUE THREAD

**Issue by tgalopin** [drufony/drufony#5]
Hi !

You project looks really interesting. I'm working on a big website project (http://mana-drain.net) and we are looking for something like your project to run the website. We're currently synchronizing sessions between Drupal and Symfony, but your project seems to be better integrated, so I wanted to try it :) .

However, I had some problems during the installation:
- Composer is searching for the Bridge Script handler, but you don't install the bridge, as you install only the DrupalBundle. I changed the composer.json locally, but even with that change, the ScriptHandler in the DrupalBundle don't have the `dumpAutoload()` method (and when I added it, I got an error: `Bangpound\Bundle\DrupalBundle\Composer\ClassMapGenerator` does not exists, so I didn't go further) ;
- drush have some problem during install:
  `array_key_exists() expects parameter 2 to be array, null given drush.inc:1620`
  `Invalid argument supplied for foreach() drush.inc:1651`
  `WD php: Warning: array_key_exists() expects parameter 2 to be array, null given in _drush_log_drupal_messages() (line 1620 of                                                     [warning]
  /var/www/drufony/vendor/drush/drush/includes/drush.inc).`

I understand that an experimental project for the moment, and I would be pleased to help you a bit with it. I know really well Symfony and I'm learning Drupal quickly :) .

Regards,
Titouan Galopin

**Comment by bangpound** [comment]
Hi Titouan.

You found the project when it was in the midst of a transition. I've taken some classes out and moved them into another project (the bridge) so they can be more easily tested outside Symfony.

You are correct though that I have fully integrated Drupal and Symfony sessions!

I should be finished with my work in a few hours, and I'll re-test the drufony setup and update this ticket to let you know it's ready.
